-- 1. ADVERTENCIA: Este comando borrará TODOS los personajes actuales de tu servidor y los inventarios de los usuarios.
-- Ejecútalo con cuidado.

DELETE FROM public.collectibles;

-- 2. Insertando nueva colección de personajes anime:

INSERT INTO public.collectibles (id, name, series, rarity, description, image_url)
VALUES
  ('char_naruto_uzumaki', 'Naruto Uzumaki', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/oKuK0pRkalIAAAAC/hinata-hinata-uzumaki.gif'),
  ('char_sakura_haruno', 'Sakura Haruno', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/04X98SH62L4AAAAC/sakura-naruto.gif'),
  ('char_hinata_hyuga', 'Hinata Hyuga', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/gxG8a8IF-sgAAAAC/ano-blushing.gif'),
  ('char_rock_lee', 'Rock Lee', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/bgK50gNqFBMAAAAC/rock-lee-naruto.gif'),
  ('char_usopp', 'Usopp', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/snEjOfTYSssAAAAC/usopp-nami.gif'),
  ('char_chopper', 'Chopper', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/LY9V-Ax-rMYAAAAC/anniversaire.gif'),
  ('char_nami', 'Nami', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/_omznfTSncQAAAAC/one-piece-nami.gif'),
  ('char_zenitsu_agatsuma', 'Zenitsu Agatsuma', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/zNAqn9XUxVMAAAAC/zenitsu-zenitsu-agatsuma.gif'),
  ('char_inosuke_hashibira', 'Inosuke Hashibira', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/J08tCPlL6dIAAAAC/inosuke-demon-slayer.gif'),
  ('char_tanjiro_kamado', 'Tanjiro Kamado', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/NXJaWuWnskgAAAAC/demon-slayer-kimetsu-no-yaiba.gif'),
  ('char_ochaco_uraraka', 'Ochaco Uraraka', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/ZSYn5yJAwLMAAAAC/izuku-midoriya-deku.gif'),
  ('char_mina_ashido', 'Mina Ashido', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/3y5svUytIpsAAAAC/mina-ashido.gif'),
  ('char_denki_kaminari', 'Denki Kaminari', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/2OjoC0gY7s0AAAAC/denki-mha.gif'),
  ('char_yuga_aoyama', 'Yuga Aoyama', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/r3CdaDTpRC0AAAAC/my-hero-academia-yuga-aoyama.gif'),
  ('char_armin_arlert', 'Armin Arlert', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/zDrvrLRzCmkAAAAC/armin-de-mika-armin-arlert.gif'),
  ('char_connie_springer', 'Connie Springer', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/5dwgtl3iCEkAAAAC/connie-conniespringer.gif'),
  ('char_sasha_blouse', 'Sasha Blouse', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/axE-S5OoecgAAAAC/attack-on-titan-sasha.gif'),
  ('char_momo_yaoyorozu', 'Momo Yaoyorozu', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/daMU_RJl2fkAAAAC/momo-yaoyorozu-yaoyorozu.gif'),
  ('char_kanao_tsuyuri', 'Kanao Tsuyuri', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/vwzzCkIJoXkAAAAC/kanao-tsuyuri.gif'),
  ('char_nezuko_kamado', 'Nezuko Kamado', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/4lPCEkjTcqUAAAAC/nezuko-nezuko-kamado.gif'),
  ('char_yui_hirasawa', 'Yui Hirasawa', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/yZT9VI3xKbMAAAAC/k-on.gif'),
  ('char_ritsu_tainaka', 'Ritsu Tainaka', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/anv0iu3cScgAAAAC/ritsu-ritsu-tainaka.gif'),
  ('char_taiga_aisaka', 'Taiga Aisaka', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/6NrCvu5CAYUAAAAC/taiga.gif'),
  ('char_yuno_gasai', 'Yuno Gasai', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/v2CrtkCiErYAAAAC/anime-yandere.gif'),
  ('char_mikoto_misaka', 'Mikoto Misaka', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/vxKvjYoi70AAAAAC/datgp-second-chance.gif'),
  ('char_tohru_honda', 'Tohru Honda', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/8zlM67t4cpYAAAAC/anime-slap.gif'),
  ('char_shoyo_hinata', 'Shoyo Hinata', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/bKYuGaSn_lQAAAAC/hinata-shoyo-haikyuu.gif'),
  ('char_tobio_kageyama', 'Tobio Kageyama', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/Hcbxpbvx3ZoAAAAC/kageyama-tobio-haikyuu.gif'),
  ('char_nobara_kugisaki', 'Nobara Kugisaki', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/-KGzQiMihX8AAAAC/nobara-nobara-kugisaki.gif'),
  ('char_yuji_itadori', 'Yuji Itadori', 'Anime Universo', 'common', 'Personaje común de la colección anime.', 'https://media.tenor.com/rrLh0TknMj8AAAAC/itadori-itadori-yuji.gif'),
  ('char_kakashi_hatake', 'Kakashi Hatake', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/7bur89G-zE8AAAAC/kakashi-kakashi-hatake.gif'),
  ('char_itachi_uchiha', 'Itachi Uchiha', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/AN2ZpYraZcoAAAAC/itachi-itachi-uchiha.gif'),
  ('char_shikamaru_nara', 'Shikamaru Nara', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/EreuGiICMPQAAAAC/temari-love.gif'),
  ('char_levi_ackerman', 'Levi Ackerman', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/kASdz_4XBN0AAAAC/levi-levi-ackerman.gif'),
  ('char_mikasa_ackerman', 'Mikasa Ackerman', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/SbgrmA2MBeIAAAAC/mikasa-ackerman-mikasa-ackermann.gif'),
  ('char_gojo_satoru', 'Gojo Satoru', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/vqwtM0yyPlUAAAAC/gojo-jujutsu-kaisen.gif'),
  ('char_megumi_fushiguro', 'Megumi Fushiguro', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/NsYi42wOtk0AAAAC/jjk-jujutsu-kaisen.gif'),
  ('char_power', 'Power', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/A8UvPwOyh34AAAAC/power-csm-power-chainsaw-man.gif'),
  ('char_makima', 'Makima', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/p_ovSabUDtkAAAAC/makima-aki.gif'),
  ('char_aki_hayakawa', 'Aki Hayakawa', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/psd3HK9CIIoAAAAC/aki-hayakawa-hayakawa.gif'),
  ('char_rem', 'Rem', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/NMAMk3d1dkEAAAAC/re-zero-anime-girl.gif'),
  ('char_ram', 'Ram', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/nltawIw3rQIAAAAC/rem-waiting.gif'),
  ('char_zero_two', 'Zero Two', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/X93U5vLdzdMAAAAC/anime-pink-hair.gif'),
  ('char_rias_gremory', 'Rias Gremory', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/rbgJ79_0WmUAAAAC/rias-gremory-highschool-dxd.gif'),
  ('char_kurumi_tokisaki', 'Kurumi Tokisaki', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/T4axEdjIpEcAAAAC/date-a-live-kurumi.gif'),
  ('char_akame', 'Akame', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/VRuor-LtjL8AAAAC/chelsea-akame-ga-kill.gif'),
  ('char_esdeath', 'Esdeath', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/Xfxjc2uL738AAAAC/anime.gif'),
  ('char_lucy_heartfilia', 'Lucy Heartfilia', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/urZdm50X_woAAAAC/fairy-tail-lucy-heartfilia.gif'),
  ('char_gray_fullbuster', 'Gray Fullbuster', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/TTVw4UM-uQMAAAAC/gray-gray-fullbuster.gif'),
  ('char_erza_scarlet', 'Erza Scarlet', 'Anime Universo', 'rare', 'Personaje raro de la colección anime.', 'https://media.tenor.com/SmC5VuEUjNoAAAAC/fairy-tail-erza-scarlet.gif'),
  ('char_madara_uchiha', 'Madara Uchiha', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/Wowk9K_O8yYAAAAC/uchiha-madara.gif'),
  ('char_obito_uchiha', 'Obito Uchiha', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/7tQurzW8Bd4AAAAC/tobi-naruto.gif'),
  ('char_pain_nagato', 'Pain (Nagato)', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/HKHuRgAHuR8AAAAC/konan-flowers.gif'),
  ('char_sukuna', 'Sukuna', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/yjNFdvGYh70AAAAC/sukuna-sukuna-smile.gif'),
  ('char_eren_yeager', 'Eren Yeager', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/KvsK9WzlCjUAAAAC/eren-jaeger.gif'),
  ('char_ken_kaneki', 'Ken Kaneki', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/Ps_wfaeWNqcAAAAC/tokyo-ghoul-anime.gif'),
  ('char_jotaro_kujo', 'Jotaro Kujo', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/HBhCgnuKxy4AAAAC/jojo-albania.gif'),
  ('char_dio_brando', 'Dio Brando', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/fGyYUZl75cwAAAAC/christmas-joy.gif'),
  ('char_light_yagami', 'Light Yagami', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/eyXeghJaXk4AAAAC/light-yagami-death-note.gif'),
  ('char_lelouch_lamperouge', 'Lelouch Lamperouge', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/kFe-oEFAmU8AAAAC/lelouch.gif'),
  ('char_alucard', 'Alucard', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/RgjzB6aVviYAAAAC/alucard-hellsing.gif'),
  ('char_guts', 'Guts', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/ds_-mzt8Wq8AAAAC/berserk-berserkiszymon.gif'),
  ('char_griffith', 'Griffith', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/8lB0rqq6UrgAAAAC/griffguts-griffith.gif'),
  ('char_rimuru_tempest', 'Rimuru Tempest', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/oXRmdVAKrhMAAAAC/rimuru-slime.gif'),
  ('char_anos_voldigoad', 'Anos Voldigoad', 'Anime Universo', 'epic', 'Personaje épico de la colección anime.', 'https://media.tenor.com/Hh53XYfsyroAAAAC/anos-voldigoad-maou-gakuin-no-futekigousha.gif'),
  ('char_goku_ultra_instinct', 'Goku Ultra Instinct', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/axi9xVrR8goAAAAC/dragon-ball-dragon-ball-z.gif'),
  ('char_saitama', 'Saitama', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/2FPcjP8vlTwAAAAC/saitama-one-punch-man.gif'),
  ('char_gojo_limitless', 'Gojo Limitless', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/ydfcJmBAKykAAAAC/gojo-gojo-satoru.gif'),
  ('char_eren_founding_titan', 'Eren Founding Titan', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/Erl7AzP71_MAAAAC/aot-eren.gif'),
  ('char_naruto_six_paths', 'Naruto Six Paths', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/e8ctHLZbGSsAAAAC/obito-obito-uchiha.gif'),
  ('char_madara_sage_mode', 'Madara Sage Mode', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/-HRp-IjKahIAAAAC/madara-vs-minato-minato-vs-madara.gif'),
  ('char_levi_awakened', 'Levi Awakened', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/-LiCmY0faWAAAAAC/eating-wataten.gif'),
  ('char_aizen_sosuke', 'Aizen Sosuke', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/LzCV-UOvyBAAAAAC/s%C5%8Dsuke-aizen-gin-ichimaru.gif'),
  ('char_jiren', 'Jiren', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/ErSmzzo4i3sAAAAC/goku-mui.gif'),
  ('char_broly', 'Broly', 'Anime Universo', 'legendary', 'Personaje legendario de la colección anime.', 'https://media.tenor.com/wqZeuP7xQL8AAAAC/vegeta-broly.gif'),
  ('char_hatsune_miku', 'Hatsune Miku', 'Anime Universo', 'mythic', 'Personaje mítico de la colección anime.', 'https://media.tenor.com/ZlYEwEcLfvQAAAAC/1.gif'),
  ('char_astolfo', 'Astolfo', 'Anime Universo', 'mythic', 'Personaje mítico de la colección anime.', 'https://media.tenor.com/x8WtNAH1UVgAAAAC/astolfo.gif'),
  ('char_2b', '2B', 'Anime Universo', 'mythic', 'Personaje mítico de la colección anime.', 'https://media.tenor.com/dEsfh9nWEYUAAAAC/nier-automata-2b.gif'),
  ('char_asuka_langley', 'Asuka Langley', 'Anime Universo', 'mythic', 'Personaje mítico de la colección anime.', 'https://media.tenor.com/en4N2EWT4SkAAAAC/anime.gif'),
  ('char_rei_ayanami', 'Rei Ayanami', 'Anime Universo', 'mythic', 'Personaje mítico de la colección anime.', 'https://media.tenor.com/vxXS1fQeiAYAAAAC/rei-ayanami-neon-genesis-evangelion.gif')
ON CONFLICT (id) DO UPDATE SET 
  series = EXCLUDED.series, 
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  rarity = EXCLUDED.rarity,
  image_url = EXCLUDED.image_url;
